### ISSUE TITLE
Add All contributors bot for github

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-frontend#14]
### Description

add all contributor's bot so that every developer gets the necessary credits

### Anything else?

https://allcontributors.org/docs/en/bot/installation

**Comment by shivamvishwakarm** [comment]
@aayushchugh  assign me this issue.

**Comment by aayushchugh** [comment]
@shivamvishwakarm done bro

**Comment by shivamvishwakarm** [comment]
@aayushchugh  please add label HACKTOBERFEST-ACCEPTED

**Comment by aayushchugh** [comment]
@shivamvishwakarm added sorry I forget it before

**Comment by shivamvishwakarm** [comment]
can you add it now

**Comment by aayushchugh** [comment]
@shivamvishwakarm I have already added it to the PR hacktoberfest need label on PR only
